window.STREAM_MASTER_PRODUCTS = [
  {
    "name": "NETFLIX 4K PREMIUN",
    "category": "Streaming",
    "price": "S/ 15",
    "duration": "30 días",
    "activation": "Inmediata, se ta correo y contraseña",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlZxmAtNgZv4CalHiYARwluAz0AkNyD0nyB0CFX0_Jb6dTaWE06E01bXQ&s=10",
    "icon": "🎬",
    "description": "Se entrega correo y contraseña. Acceso para 1 dispositivo. Activación inmediata y soporte durante la vigencia del servicio.",
    "featured": true,
    "offer": true,
    "sales": 200,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "DISNEY PREMUN + 7 SPN",
    "category": "Streaming",
    "price": "S/ 10",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0kO8lj_3jvcz0RcNmuu9oix-AVjh67A7rfowVNQ9KCQ&s=10",
    "icon": "🏰",
    "description": "Se entrega correo y contraseña. Acceso para 1 dispositivo. Activación inmediata y soporte durante la vigencia del servicio.",
    "featured": true,
    "offer": true,
    "sales": 195,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "PRIME VIDEO",
    "category": "Streaming",
    "price": "S/ 7",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFySbdVDly7OkJeQ1pOX9mW3KtVGRypNcSscme-nSTg&s=10",
    "icon": "▶️",
    "description": "Se entrega correo y contraseña. Acceso para 1 dispositivo. Activación inmediata y soporte durante la vigencia del servicio.",
    "featured": true,
    "offer": false,
    "sales": 190,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "HBO MAX",
    "category": "Streaming",
    "price": "S/ 9",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPvoqjU2lpyz4kXmVu8NEgv7VvXuLNKRJ-df0ZhLXzhQ&s=10",
    "icon": "⭐",
    "description": "Se entrega correo y contraseña. Acceso para 1 dispositivo. Activación inmediata y soporte durante la vigencia del servicio.",
    "featured": true,
    "offer": false,
    "sales": 185,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "PARAMOUNT",
    "category": "Streaming",
    "price": "S/ 16",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8dBKoTIGRLlkvX6QhxOF7BA_dv0Dj56os_geROobdJQ&s=10",
    "icon": "⛰️",
    "description": "Se entrega correo y contraseña. Acceso para 1 dispositivo. Activación inmediata y soporte durante la vigencia del servicio.",
    "featured": true,
    "offer": false,
    "sales": 180,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "IPTV",
    "category": "TV y Deportes",
    "price": "S/ 15",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTizZKMcd5RPQymF2T9NWu3uxUTpyvdpWhBDmGWXM6cA&s=10",
    "icon": "📺",
    "description": "Se entrega correo y contraseña. Acceso para 3 dispositivo. Activación inmediata y soporte durante la vigencia del servicio.",
    "featured": true,
    "offer": true,
    "sales": 175,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "Peacock",
    "category": "TV y Deportes",
    "price": "S/ 16",
    "duration": "1 mes",
    "activation": "1 dispositivo",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBQ4s00EQ-cMnpUcRGxbTD5-i4acM_a4iTzp9i1GGCDQ&s=10",
    "icon": "🦚",
    "description": "Se entrega correo y contraseña. Acceso para 1 dispositivo. Activación inmediata y soporte durante la vigencia del servicio.",
    "featured": true,
    "offer": false,
    "sales": 170,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "APPLE TV",
    "category": "Streaming",
    "price": "S/ 12",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1wg0CPmETz46NfdYN9qCs4aNjZCXjgvKAy9wdQ_pJKA&s=10",
    "icon": "🍎",
    "description": "Se entrega correo y contraseña. Acceso para 1 dispositivo. Activación inmediata y soporte durante la vigencia del servicio",
    "featured": true,
    "offer": false,
    "sales": 165,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "YouTube premium + YouTube Music NO RENOVABLE",
    "category": "Streaming",
    "price": "S/ 6",
    "duration": "30 días",
    "activation": "A tu correo ",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-riDq51C5hsqDqdJ9_Qz72cTeu6aKovOWyfs8Int1iA&s",
    "icon": "📹",
    "description": "Activación directamente a tu correo electrónico. Es necesario que tu cuenta no pertenezca a ningún grupo familiar de YouTube Premium. Solo debes proporcionarnos tu correo, recibirás una invitación, la aceptas y el servicio quedará activo en pocos minutos. Servicio no renovable automáticamente.",
    "featured": false,
    "offer": true,
    "sales": 160,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "Canva Pro",
    "category": "Diseño y Productividad",
    "price": "S/ 15",
    "duration": "1 año",
    "activation": "A tu correo",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoP3utzNEQNS-igKIxHBzZaf_B4B_OpkNPuMd0tdpEyQ&s=10",
    "icon": "🎨",
    "description": "Herramienta de diseño para flyers, tareas, publicaciones y trabajos.",
    "featured": false,
    "offer": true,
    "sales": 155,
    "rating": 5,
    "badge": "Premium"
  },
  {
    "name": "Microsoft 365",
    "category": "Diseño y Productividad",
    "price": "25",
    "duration": "1 año ",
    "activation": "A tu correo",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgZMTp357wYp3VxQ4ZVrRfanSwmt6Q4FutRYDtSk7ngA&s=10",
    "icon": "💼",
    "description": "Herramientas de productividad para documentos, hojas de cálculo y presentaciones.",
    "featured": false,
    "offer": false,
    "sales": 150,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Figma Pro",
    "category": "Diseño y Productividad",
    "price": "S/ 35",
    "duration": "1 año",
    "activation": "A tu correo",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLByr5oMJbeROvPhUgh_TpfRT1v3Zi9RuYjGcVMLmlPA&s=10",
    "icon": "🧩",
    "description": "Activación a tu correo. Incluye herramientas profesionales para diseño UI/UX, prototipos interactivos, colaboración en equipo, historial de versiones, bibliotecas compartidas y funciones avanzadas para diseñadores.",
    "featured": false,
    "offer": false,
    "sales": 145,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Gemini Pro",
    "category": "IA",
    "price": "25",
    "duration": "1 Año",
    "activation": "A tu correo",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyKVECqV1QLECKccpyyd5t97qUCdDmQCtLEOGR-EyCOQ&s=10",
    "icon": "🤖",
    "description": "IA para estudiar, redactar, investigar y crear contenido.",
    "featured": false,
    "offer": false,
    "sales": 140,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Super Grok",
    "category": "IA",
    "price": "180",
    "duration": "1 año",
    "activation": "A tu correo",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcvXiq07LPSAmqoQzGvwIXoKLRkV6nDL82hXZGCFvRKA&s=10",
    "icon": "⚡",
    "description": "Activación a tu correo. Incluye chat inteligente, generación de imágenes y videos ilimitados, ayuda para programación, investigación, análisis de documentos y asistencia en tiempo real.",
    "featured": false,
    "offer": true,
    "sales": 135,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Perplexity",
    "category": "IA",
    "price": "Consultar",
    "duration": "1 año",
    "activation": "A tu correo",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSKOpdm8bHI5jAe2YN9eVTgz_GcE4PQV6w8ea1ws8a7A&s=10",
    "icon": "🔎",
    "description": "Activación a tu correo. Realiza búsquedas con IA, obtén respuestas con fuentes confiables, analiza documentos, investiga y genera contenido de forma rápida.",
    "featured": false,
    "offer": false,
    "sales": 130,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Likes, seguidores y comentarios",
    "category": "Redes Sociales",
    "price": "Consultar",
    "duration": "Según pedido",
    "activation": "Segun catidad de likes , seguidores , vistas. Menos de 8 horas ",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtSmJweYcJIWGl4mSuYrll5pExk81hWcqk4dJuP22DkQ&s=10",
    "icon": "📈",
    "description": "Servicio para mejorar interacción en cualquier red social.",
    "featured": false,
    "offer": false,
    "sales": 125,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Spotify",
    "category": "Streaming",
    "price": "10",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHZc9Zjr0_R7UY5UmKRdkn5YX6_1S2zW7iRu5abplxXw&s",
    "icon": "⭐",
    "description": "Activación a tu propio correo O se te da correo y contraseña. Conserva tu cuenta, listas de reproducción y canciones favoritas. Disfruta de Spotify Premium sin anuncios y con descargas para escuchar sin conexión.",
    "featured": false,
    "offer": false,
    "sales": 120,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Dezzer",
    "category": "Streaming",
    "price": "6",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdilbh7WW5erKFSSNokjgiBOpr75ELutnNB42qoN8zkg&s=10",
    "icon": "⭐",
    "description": "Accede a Deezer Premium y disfruta de millones de canciones sin anuncios, con audio de alta calidad, descargas offline y reproducción ilimitada.",
    "featured": false,
    "offer": false,
    "sales": 115,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Microsoft office 365 + 5 invitaciones ",
    "category": "Diseño y Productividad",
    "price": "60",
    "duration": "1 año ",
    "activation": "30 mins",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdB321Ix9H4ZtsNimnDSi-h2tzl-HVwJsoFvEYUMI34A&s=10",
    "icon": "⭐",
    "description": "Se entrega correo y contraseña. Incluye Microsoft 365 completo por 1 año con Word, Excel, PowerPoint, Outlook y más. Además, contaras con 5 invitaciones, para que otros tambien puedan acceder a los beneficios, cada una con 1 TB de almacenamiento en OneDrive (5 TB en total). El almacenamiento es individual para cada invitación, no se comparte entre usuarios.",
    "featured": false,
    "offer": false,
    "sales": 110,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Gemini pro + 5 invitaciones ",
    "category": "Streaming",
    "price": "35",
    "duration": "1 año",
    "activation": "A tu correo ",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyKVECqV1QLECKccpyyd5t97qUCdDmQCtLEOGR-EyCOQ&s=10",
    "icon": "⭐",
    "description": "Activación en tu propio correo. Incluye Gemini Pro por 1 año y 5 invitaciones. Para la activación se requiere acceso temporal a tu cuenta (correo y contraseña); una vez finalizado el proceso, podrás cambiar tu contraseña con total tranquilidad.",
    "featured": false,
    "offer": false,
    "sales": 105,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "YouTube premium + YouTube Music  RENOVABLE ",
    "category": "Streaming",
    "price": "12",
    "duration": "30 días",
    "activation": "A tu correo ",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-riDq51C5hsqDqdJ9_Qz72cTeu6aKovOWyfs8Int1iA&s",
    "icon": "⭐",
    "description": "Activación en tu propio correo. Solo necesitamos tu correo electrónico para la activación. Tu cuenta no debe pertenecer a ningún grupo familiar de YouTube Premium. El servicio es renovable, por lo que podrás mantener tu suscripción activa de forma continua mientras renueves el plan.",
    "featured": false,
    "offer": true,
    "sales": 100,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "YouTube premium + YouTube Music familiar NO RENOVABLE",
    "category": "Streaming",
    "price": "12.50",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM9oDl5fOnHmg8-6qhKPpB3IizqPqldJNg9T4v0f5hJw&s=10",
    "icon": "⭐",
    "description": "Activación en tu propio correo. Incluye YouTube Premium + YouTube Music Familiar por 1 mes. Para la activación no debes aver estado en un grupo familiar solo necesitamos tu correo y contraseña. Una vez finalizado el proceso, podrás cambiar tu contraseña. Servicio no renovable.",
    "featured": false,
    "offer": true,
    "sales": 95,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "YouTube premium + YouTube Music familiar RENOVABLE",
    "category": "Streaming",
    "price": "35",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7jPt1jgFT9PeolFeoNy3IgnbLwD3eBNJKOno-70BoMw&s=10",
    "icon": "⭐",
    "description": "Activación en tu propio correo. Incluye YouTube Premium + YouTube Music Familiar por 1 mes. Para la activación no debes aver estado en un grupo familiar solo necesitamos tu correo y contraseña. Una vez finalizado el proceso, podrás cambiar tu contraseña. Servicio renovable.",
    "featured": false,
    "offer": false,
    "sales": 90,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Crunchyrroll",
    "category": "Streaming",
    "price": "7",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR09nep7eKrJV8VbedtYs2mOjuDhIVM5_6PRlyxkRZwYg&s=10",
    "icon": "⭐",
    "description": "Se entrega correo y contraseña. Disfruta de Crunchyroll Premium sin anuncios, acceso ilimitado a miles de animes, estrenos simultáneos con Japón y reproducción en alta calidad. Activación inmediata.",
    "featured": false,
    "offer": false,
    "sales": 85,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Autodesk Suite",
    "category": "Streaming",
    "price": "25",
    "duration": "1 año ",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqMvfHI3Gd7yBaI00GAqgQo34SpVjZl8B-9DNE3nT7Cw&s=10",
    "icon": "⭐",
    "description": "Activación a tu correo. Accede por 1 año a Autodesk Suite, incluyendo AutoCAD, Revit, Civil 3D, Inventor, 3ds Max, Maya, Navisworks y más herramientas profesionales para arquitectura, ingeniería, diseño y construcción.",
    "featured": false,
    "offer": false,
    "sales": 80,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "surfshark",
    "category": "Diseño y Productividad",
    "price": "10",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://www.google.com/imgres?q=surfshark&imgurl=https%3A%2F%2Fimages-eds-ssl.xboxlive.com%2Fimage%3Furl%3D4rt9.lXDC4H_93laV1_eHHFT949fUipzkiFOBH3fAiZZUCdYojwUyX2aTonS1aIwMrx6NUIsHfUHSLzjGJFxxuO4Q1tKCo0hwnses7q5bXK1_NgVkNKV3PeSg2B042yfP2DMtFQV8fi5YYkb89qehIL0HHc6fA_UpI__1.nG3vU-%26format%3Dsource&imgrefurl=https%3A%2F%2Fapps.microsoft.com%2Fdetail%2Fxp9kn848dqpdk9%3Fhl%3Des-es%26gl%3DUS&docid=gdNej-nV5pbRHM&tbnid=nvgFrZL9OokyIM&vet=12ahUKEwitsanny7GVAxXalJUCHSHCLBcQnPAOegQIPhAA..i&w=2160&h=2160&hcb=2&ved=2ahUKEwitsanny7GVAxXalJUCHSHCLBcQnPAOegQIPhAA",
    "icon": "⭐",
    "description": "Se entrega correo y contraseña. Disfruta de Surfshark VPN por 1 mes en 1 dispositivo. Navega con mayor privacidad y seguridad, protege tu conexión y accede a contenido con restricciones geográficas. Activación inmediata.",
    "featured": false,
    "offer": false,
    "sales": 75,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "express vpn",
    "category": "Diseño y Productividad",
    "price": "10",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNtn3t--Hhf0Ckdl_BeaKJva9Q8XU2PQyPBmWMPrvNIQ&s=10",
    "icon": "⭐",
    "description": "Se entrega correo y contraseña. Disfruta de ExpressVPN por 1 mes para 1 dispositivo. Protege tu privacidad, navega de forma segura y accede a contenido de diferentes países con una conexión rápida y estable.",
    "featured": false,
    "offer": false,
    "sales": 70,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "Chact gpt plus ",
    "category": "IA",
    "price": "18",
    "duration": "30 días",
    "activation": "Inmediata",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlmbog59iR9GTdcDRNcuNNXgzNl2ezCQ3fMO1Ypj6LyA&s=10",
    "icon": "⭐",
    "description": "Se entrega correo y contraseña. Acceso para 1 dispositivo. Al iniciar sesión por primera vez, se proporcionará un único código de verificación para garantizar el uso en un solo dispositivo. El código solo se entrega una vez. No hay reclamos ni reembolsos por pérdida del acceso debido al uso en otros dispositivos. Si la sesión se cierra automáticamente, envíanos una captura de pantalla para verificar el caso y brindarte soporte si corresponde.",
    "featured": false,
    "offer": false,
    "sales": 65,
    "rating": 5,
    "badge": "Disponible"
  },
  {
    "name": "DGO + LIGA 1 MAX",
    "category": "Streaming",
    "price": "28",
    "duration": "30 días",
    "activation": "InmediatA",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTakB1ub2BuU7PGtAgQG8LTKdUZao70vHzjmGPpmOodLw&s=10",
    "icon": "⭐",
    "description": "Activación en tu TV mediante código (recomendado). Acceso exclusivo para 1 dispositivo. Para garantizar la estabilidad del servicio, el uso en más de un dispositivo no está permitido. Si se detecta acceso simultáneo desde otro equipo, la garantía se perderá y el servicio podrá ser suspendido. Si decides iniciar sesión en un televisor, celular o cualquier otro dispositivo con las credenciales, aplicarán las mismas condiciones.",
    "featured": false,
    "offer": false,
    "sales": 60,
    "rating": 5,
    "badge": "Disponible"
  }
];
window.STREAM_MASTER_WHATSAPP = '51992001097';
